name: Deploy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Deploy
        steps: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          ./upload
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}